In [2]:
#Decision_Tree
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score


data = load_iris()
X = data.data
y = data.target


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [3]:
#KNN
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

iris = load_iris()
X = iris.data     
y = iris.target  



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1
)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy * 100, "%")



Confusion Matrix:
 [[14  0  0]
 [ 0 18  0]
 [ 0  1 12]]
Accuracy: 97.77777777777777 %


In [4]:
#Naive_Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris


data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


model = GaussianNB()
model.fit(X_train, y_train)


print("Prediction:", model.predict(X_test[:5]))


Prediction: [2 0 2 2 2]


In [6]:
#Gradient_Discent
import numpy as np


X = np.array([1, 2, 3, 4, 5])
y = np.array([3, 4, 2, 4, 5])

X = X.reshape(-1, 1)

theta_0 = 0
theta_1 = 0


alpha = 0.01  
epochs = 1000  

m = len(X)


for i in range(epochs):
    y_pred = theta_0 + theta_1 * X.flatten()
    
    d_theta_0 = (-2/m) * sum(y - y_pred)
    d_theta_1 = (-2/m) * sum((y - y_pred) * X.flatten())
    
    theta_0 = theta_0 - alpha * d_theta_0
    theta_1 = theta_1 - alpha * d_theta_1

print("Theta 0 (intercept):", theta_0)
print("Theta 1 (slope):", theta_1)


x_new = 6
prediction = theta_0 + theta_1 * x_new
print("Prediction for x = 6:", prediction)

Theta 0 (intercept): 2.328094660112053
Theta 1 (slope): 0.4199166261431282
Prediction for x = 6: 4.847594416970822


In [7]:
#Batch_Gradient
import numpy as np


X = np.array([
    [2100, 3],
    [1600, 2],
    [2400, 4],
    [1416, 2],
    [3000, 4]
])

y = np.array([400000, 330000, 369000, 232000, 540000])

m = X.shape[0]


X_b = np.c_[np.ones((m, 1)), X]


theta = np.zeros(X_b.shape[1])


alpha = 0.00000001  
epochs = 10000


for i in range(epochs):
    y_pred = X_b.dot(theta)
    gradients = (1/m) * X_b.T.dot(y_pred - y)
    theta = theta - alpha * gradients

print("Final theta values:", theta)


new_data = np.array([1, 2000, 3])
pred = new_data.dot(theta)

print("Predicted price:", pred)

Final theta values: [  0.26287513 177.04330479  -0.69496886]
Predicted price: 354084.7875477099


In [8]:
#linear_regression
def mean(values):
    return sum(values) / len(values)

def covariance(x, y):
    xm = mean(x)
    ym = mean(y)
    cov = 0
    for i in range(len(x)):
        cov += (x[i] - xm) * (y[i] - ym)
    return cov

def variance(values):
    m = mean(values)
    var = 0
    for val in values:
        var += (val - m) ** 2
    return var

def train_linear_regression(x, y):
    m = covariance(x, y) / variance(x)
    b = mean(y) - m * mean(x)
    return m, b

def predict(x, m, b):
    return m * x + b



X = [1, 2, 3, 4, 5]
Y = [2, 4, 5, 4, 5]

m, b = train_linear_regression(X, Y)

print("Slope (m):", m)
print("Intercept (b):", b)


print("Prediction for x=6:", predict(6, m, b))

Slope (m): 0.6
Intercept (b): 2.2
Prediction for x=6: 5.8


In [9]:
#multi_linear
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([
    [2100, 3],
    [1600, 2],
    [2400, 4],
    [1416, 2],
    [3000, 4]
])

y = np.array([400000, 330000, 369000, 232000, 540000])
model = LinearRegression()


model.fit(X, y)


print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

pred = model.predict([[2000, 3]])
print("Predicted price for 2000 sq ft, 3 rooms:", pred)

Intercept: 17580.560249577044
Coefficients: [   305.74060835 -95471.40257377]
Predicted price for 2000 sq ft, 3 rooms: [342647.56921877]
